config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"
  get 'home/index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: {:new => ''}
  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  validates :title, presence: true, length: { maximum: 140 }
  validates :text, presence: true, length: { maximum: 4000 }
  has_many :comments, dependent: :destroy


  def subject
    title  
  end

  def last_comment
    comments.last    
  end
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, length: { maximum: 4000 }
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create, :update, :destroy]

  def index
    @articles = Article.all
    
  end

  def show
    @article = Article.find(params[:id])
    
  end

  def new    
  end
  
 def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article # прерывает запрос и возвращает в браузер редирект команду на определенную страницу и браузер следующим запросом эту страницу получает
    else
      render action: 'new'   # render не прерывает запрос текущий, а продолжает его дальше   
    end

  end

  def edit
    @article = Article.find(params[:id])
    
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article #делаем редирект на эту самую статью
    else
      render action: 'edit'      
    end    
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
    #redirect_to action: :index #(так тоже можно)
  end

  private  #защита от хакинга

  def article_params # возвращает список обьектов
    params.require(:article).permit(:title, :text)# конфигурация этих обьектов
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :authenticate_user!, :only => [:create]


  def create
    @article = Article.find(params[:article_id])
    @c = @article.comments.new(comment_params)
    @c.autor = current_user.username
    @c.save
    redirect_to article_path(@article)
    
  end

   private  #от хакинга

  def comment_params
    params.require(:comment).permit(:autor, :body)
  end



end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new    
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'      
    end

  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def terms    
  end

  def about    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/create.html.erb
<h1>Thank you</h1>
<p>New article has been created</p>

<%= link_to 'Show all articles', articles_path %> 

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
	<p>
		<%= f.label :title %><br/>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :text %><br/>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>
	<% end %>

app/views/articles/index.html.erb
<h2>List of articles</h2>


<% @articles.each do |article| %>


<div class="media">
  <img src="..." class="mr-3" alt="...">
  <div class="media-body">
    <h5 class="mt-0"><%= article.title %></h5>
    <p>
    	<%= article.text %>
    </p>
     <p>
		<%= link_to 'Show', article_path(article) %> |
		<%= link_to 'Edit', edit_article_path(article) %> |
		<%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you shure?'} %>
	 </p>
          
  </div>
 
</div>
  
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1></br>

<%= form_for :article, url: articles_path do |f| %>
	<p>
		<h4><%= f.label :title %></h4>
		<%= f.text_field :title, class: "form-control", placeholder: "Article's name", style: "width: 400px"%>
	</p>
	<p>
		<h4><%= f.label :text %></h4>
		<%= f.text_area :text , class: "form-control", placeholder: "Text input", style: "width: 800px" %>
	</p>

	<p>
		<%= f.submit %>
	</p>
	<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
	<%= @article.text %>
</p> 

<h2>Comments</h2>

<% @article.comments.each do |comment| %>
	<p>
		<i><%= comment.autor %> said:</i><br/>
	</p>
	<p>
		<%= comment.body %>
	</p>
<% end %>
<h2>Add comment</h2>
<p>

	<%= form_for([@article, @article.comments.build]) do |f| %>
		
		<p>
			<%= f.label :body %><br/>
			<%= f.text_area :body %>
		</p>

		<p>
			<%= f.submit %>
		</p>
	<% end %>
</p>

app/views/contacts/create.html.erb
<p>Thanks!</p>

app/views/contacts/new.html.erb
<h1><%= t('contacts.contact_us') %></h1>

<%= form_for :contact, url: contacts_path do |f| %>

	<% if @contact && @contact.errors.any? %>
	<p>
		<ul>
		<% @contact.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</p>
	<% end %>

	<p>
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :message %><br/>
		<%= f.text_area :message %>
	</p>

	<p>
		<%= f.submit 'Send message' %>
	</p>
	<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="/assets/application.js" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link data-require="bootstrap@*" data-semver="4.1.3" rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
    <script data-require="bootstrap@*" data-semver="4.1.3" src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
     <%= link_to "Blog", home_index_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li>
            <%= link_to "Articles", articles_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "New article", new_article_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Terms", terms_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Contacts", contacts_path, class: "nav-link" %>
          </li>
        </ul>
          <ul class="nav navbar-nav navbar-right">
            
              <% if user_signed_in? %>
        
                <li>Hello, <%= current_user.username %> | <%= link_to 'Sing Out', destroy_user_session_path, method: :delete %></li>
              <% else %>

                <li><%= link_to 'Sing In', new_user_session_path %></li>
              <% end %>         
          
          </ul>
        
      </div>
    </nav>
    


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About us</h2>

app/views/pages/terms.html.erb
<h2>Our terms</h2>